//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Ekranı.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgretmen
    {
        public int OgrtID { get; set; }
        public string OgrtAd { get; set; }
        public string OgrtSoyad { get; set; }
        public string OgrtSifre { get; set; }
        public string OgrtNumara { get; set; }
    }
}
